---
### Win 2022 H21 Harden ###
ansible_user: "ansible"
ansible_password: "aG0lch1n34"
#  #ansible_ssh_port: 5985
ansible_ssh_port: 5986
ansible_connection: winrm
ansible_winrm_transport: ntlm
ansible_winrm_server_cert_validation: ignore

